'use strict'

const express = require('express')
const router = express.Router()
const seasons = require('./seasons.js')
const emailReminders = require('./emailReminders.js')

router.route('/seasons')
  .get(seasons.seasonsGet)
  .post(seasons.seasonsPost)
router.route('/seasons/:seasonId')
  .get(seasons.seasonsSeasonIdGet)
  .put(seasons.seasonsSeasonIdPut)
  .delete(seasons.seasonsSeasonIdDelete)
router.route('/seasons/:seasonId/competitions')
  .get(seasons.seasonsSeasonIdCompetitionsGet)
  .post(seasons.seasonsSeasonIdCompetitionsPost)
router.route('/seasons/:seasonId/competitions/:competitionId')
  .get(seasons.seasonsSeasonIdCompetitionsCompetitionIdGet)
  .put(seasons.seasonsSeasonIdCompetitionsCompetitionIdPut)
  .delete(seasons.seasonsSeasonIdCompetitionsCompetitionIdDelete)
router.route('/seasons/:seasonId/competitions/:competitionId/fixtures')
  .get(seasons.seasonsSeasonIdCompetitionsCompetitionIdFixturesGet)
  .post(seasons.seasonsSeasonIdCompetitionsCompetitionIdFixturesPost)
router.route('/seasons/:seasonId/competitions/:competitionId/fixtures/:fixtureId')
  .get(seasons.seasonsSeasonIdCompetitionsCompetitionIdFixturesFixtureIdGet)
  .put(seasons.seasonsSeasonIdCompetitionsCompetitionIdFixturesFixtureIdPut)
  .delete(seasons.seasonsSeasonIdCompetitionsCompetitionIdFixturesFixtureIdDelete)
router.route('/seasons/:seasonId/competitions/:competitionId/fixtures/:fixtureId/matches')
  .get(seasons.seasonsSeasonIdCompetitionsCompetitionIdFixturesFixtureIdMatchesGet)
  .post(seasons.seasonsSeasonIdCompetitionsCompetitionIdFixturesFixtureIdMatchesPost)
router.route('/seasons/:seasonId/competitions/:competitionId/fixtures/:fixtureId/matches/:matchId')
  .get(seasons.seasonsSeasonIdCompetitionsCompetitionIdFixturesFixtureIdMatchesMatchIdGet)
  .put(seasons.seasonsSeasonIdCompetitionsCompetitionIdFixturesFixtureIdMatchesMatchIdPut)
  .delete(seasons.seasonsSeasonIdCompetitionsCompetitionIdFixturesFixtureIdMatchesMatchIdDelete)
router.route('/seasons/:seasonId/competitions/:competitionId/teams')
  .get(seasons.seasonsSeasonIdCompetitionsCompetitionIdTeamsGet)
  .post(seasons.seasonsSeasonIdCompetitionsCompetitionIdTeamsPost)
router.route('/seasons/:seasonId/competitions/:competitionId/teams/:teamId')
  .get(seasons.seasonsSeasonIdCompetitionsCompetitionIdTeamsTeamIdGet)
  .put(seasons.seasonsSeasonIdCompetitionsCompetitionIdTeamsTeamIdPut)
  .delete(seasons.seasonsSeasonIdCompetitionsCompetitionIdTeamsTeamIdDelete)
router.route('/seasons/:seasonId/competitions/:competitionId/teams/:teamId/contacts')
  .get(seasons.seasonsSeasonIdCompetitionsCompetitionIdTeamsTeamIdContactsGet)
  .post(seasons.seasonsSeasonIdCompetitionsCompetitionIdTeamsTeamIdContactsPost)
router.route('/seasons/:seasonId/competitions/:competitionId/teams/:teamId/contacts/:contactId')
  .get(seasons.seasonsSeasonIdCompetitionsCompetitionIdTeamsTeamIdContactsContactIdGet)
  .put(seasons.seasonsSeasonIdCompetitionsCompetitionIdTeamsTeamIdContactsContactIdPut)
  .delete(seasons.seasonsSeasonIdCompetitionsCompetitionIdTeamsTeamIdContactsContactIdDelete)
router.route('/reminders/email')
  .get(emailReminders.remindersEmailGet)
  .put(emailReminders.remindersEmailPut)
router.route('/reminders/email/body')
  .get(emailReminders.remindersEmailBodyGet)
  .put(emailReminders.remindersEmailBodyPut)
router.route('/reminders/email/smtp')
  .get(emailReminders.remindersEmailSMTPGet)
  .put(emailReminders.remindersEmailSMTPPut)
router.route('/reminders/email/next')
  .get(emailReminders.remindersEmailNextGet)

module.exports = router
